Update overlayrw

diff --git a/module/common/overlayrw b/module/common/overlayrw
--- a/module/common/overlayrw
+++ b/module/common/overlayrw
@@ -1,15 +1,18 @@
 #!/system/bin/sh
-MODPATH="/data/adb/modules/overlayfs"
-if [ -d $1 ] && [ ! -L $1 ];then
-mkdir -p $MODPATH$1
-#setfattr -n trusted.overlay.opaque -v y $MODPATH$1
-mkdir -p $MODPATH/zoption$1
-mount -t overlay kakathic -o upperdir=$MODPATH$1,lowerdir=$1,workdir=$MODPATH/zoption$1 $1 && echo "Mount: $1 done" || echo "Mount: $1 failure !"
+MODP="/data/adb/modules/overlayfs"
+if [ -d $1 ];then
+mkdir -p $MODP$1
+setfattr -n trusted.overlay.opaque -v y $MODP$1 2>/dev/null
+mkdir -p $MODP/zoption$1
+chcon -Rh "$(ls -nZld "$1" | awk '{print $5}')" "$MODP$1"
+chmod -R 755 "$MODP$1"
+chown -Rh $(ls -nZld "$1" | awk '{print $3":"$4}') "$MODP$1"
+mount -t overlay kakathic -o upperdir=$MODP$1,lowerdir=$1,workdir=$MODP/zoption$1 $1 && echo "Mount: $1 done" || echo "Mount: $1 failure !"
 elif [ -z $1 ] || [ "$1" == "--help" ];then
 echo "Use: overlayrw [path_folder_rw]"
 echo "Instruct: overlayrw /system/app"
 echo "After running the command, you can edit files in that directory"
 else
-echo "Error: Path is not directory, link";
+echo "Error: Path is not directory";
 exit 1
 fi
