Update overlayrw

diff --git a/module/common/overlayrw b/module/common/overlayrw
--- a/module/common/overlayrw
+++ b/module/common/overlayrw
@@ -4,8 +4,8 @@ MODTMP="/dev"
 if [ -d $1 ] && [ ! -L $1 ];then
 mkdir -p $MODPATH$1
 #setfattr -n trusted.overlay.opaque -v y $MODPATH$1
-mkdir -p $MODPATH/zption/tmp$1
-mount -t overlay kakathic -o upperdir=$MODPATH$1,lowerdir=$1,workdir=/$MODTMP/overlayrw$1 $1 && echo "Mount: $1 done" || echo "Mount: $1 failure !"
+mkdir -p $MODTMP/overlayrw$1
+mount -t overlay kakathic -o upperdir=$MODPATH$1,lowerdir=$1,workdir=$MODTMP/overlayrw$1 $1 && echo "Mount: $1 done" || echo "Mount: $1 failure !"
 elif [ -z $1 ] || [ "$1" == "--help" ];then
 echo "Use: overlayrw [path_folder_rw]"
 echo "Instruct: overlayrw /system/app"
