Update overlayrw

diff --git a/module/common/overlayrw b/module/common/overlayrw
--- a/module/common/overlayrw
+++ b/module/common/overlayrw
@@ -1,1 +1,9 @@
-
+if [ -d $1 ] && [ ! -L $1 ];then
+mkdir -p $MODPATH$1
+#setfattr -n trusted.overlay.opaque -v y $MODPATH$1
+mkdir -p $MODPATH/zption/tmp$1
+mount -t overlay kakathic -o upperdir=$MODPATH$1,lowerdir=$1,workdir=/$MODPATH/zption/tmp$1 $1 && echo "Mount: $1 done." || echo "Mount: $1 failure."
+else
+echo "Error: Path is not directory, link";
+exit 1
+fi
